### ISSUE TITLE
uspGetStandingPublisherList SELECT문 칼럼추가

### ISSUE THREAD

**Issue by hanzinhee** [bonoman77/StandingService#5]
추가된 칼럼 CongregationName, Gender
SELECT 
	p.PublisherID  
	, m.MetroID
	, m.MetroName 
	, c.CircuitID
	, c.CircuitName 
        , g.CongregationName <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	, p.PublisherName
	, p.Gender <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	, p.ServantTypeID 
	, i2.Item AS ServantType 
	, p.Mobile 
	, CASE WHEN p.EndDate IS NULL THEN '봉사중' ELSE '중단' END AS EndKind
	, CONVERT(char(10), p.CreateDate, 121) AS CreateDate

**Comment by bonoman77** [comment]
감사합니다. 추후 백업 예정입니다.
